name: FTP Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/*' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy over FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: hosting213449.ae972.netcup.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /rafa-brandao.com/httpdocs/
          local-dir: ./
          timeout: 60000
